### ISSUE TITLE
cannot reproduce the result in the essay

### ISSUE THREAD

**Issue by HZIH** [wpy1999/BAS#3]
Your work is really great. I have trained a new vgg16 model based on your public code and default parameters. However, my test result is  smaller than the result in the essay. I have tried change the batch size to 64, the result is improved but still smaller than the result in the essay. I wonder whether the default parameters are right and what is the batch size of the vgg16. I'll appreciate it if you can help me figure out my problem, thanks

**Comment by wpy1999** [comment]
Hello, we set batch_size=32 for all backbones on CUB. On VGG16, we picked different seeds to get better results. For different seeds, GT_loc is around 90±1%. Usually the higher classification accuracy, the higher localization accuracy obtained by BAS. In addition topk is set based on the best results，for different weights, you can try to change the value of k. I hope this can be helpful to you.
