### ISSUE TITLE
code for visualization

### ISSUE THREAD

**Issue by LinSY546749** [wpy1999/BAS#5]
Hello！Could you provide the code for visual experimental results(activation map and bbox)?
<img width="530" alt="1683708934429" src="https://github.com/wpy1999/BAS/assets/71642276/3b271150-4a81-4dab-a9f4-4f72c1668e70">

**Comment by wpy1999** [comment]
Hi, we highly recommend you to download the code from BAS-Extension, we provide the generation of activation maps and bboxes in evaluator.py in BAS-Extension.

**Comment by wpy1999** [comment]
Hi, we highly recommend you to download the code from BAS-Extension (https://github.com/wpy1999/BAS-Extension/tree/main/WSOL), we provide the generation of activation maps and bbox in evaluator.py in BAS-Extension.
